[build]
publish = "public"

[functions]
directory = "functions/"

[template.environment]
INVESTEC_CLIENT_ID = "Investec Client ID"
INVESTEC_SECRET = "Investec Secret"
INVESTEC_API_KEY = "Investec API Key"
TRANSACTIONAL_ACCOUNT_NUMBER = "Transaction Account Number"
SAVINGS_ACCOUNT_NUMBER = "Savings Account Number"
FACILITY="Your credit facility"
MIN_BALANCE="Your desired minimum balance"
